### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by rbanders** [rbanders/ThinkPython2#1]
Receiving the above error on Exercise 5.9 when I try to run the _**do_n**_ code.  See below for problem text from Textbook.  Code will run the called function the first time, but seemingly not run it again.  Code from _**print_n**_ copied directly from Textbook.

> As an exercise, draw a stack diagram for _**print_n**_ called with _**s = 'Hello'**_ and _**n=2**_. Then write a function called _**do_n**_ that takes a function object and a number, _**n**_, as arguments, and that calls the given function _**n**_ times.

**Comment by rbanders** [comment]
Full output text from PyCharm below for reference when I run the 5.9 code:

> Traceback (most recent call last):
  File "C:\Users\rbanders\PycharmProjects\ThinkPython2\Exercise 5.9.py", line 13, in <module>
    do_n(print_n('Hello', 2), 2)
  File "C:\Users\rbanders\PycharmProjects\ThinkPython2\Exercise 5.9.py", line 10, in do_n
    function()
TypeError: 'NoneType' object is not callable
Hello
Hello
Process finished with exit code 1

**Comment by maldata** [comment]
Had a few moments while compiling again. We can step through this from the beginning to look at the behavior. Python reads through this script starting from the top, and first stores your definition of `print_n()`, then it stores your definition of `do_n()`, then it gets to a function call:

`do_n(print_n('Hello', 2), 2)`

The first thing it needs to do is figure out what `print_n('Hello', 2)` is, because it needs to use that result as an argument to `do_n()`. So, it calls `print_n('Hello', 2)`, which prints `Hello`, calls itself, prints `Hello`, calls itself, and then the third invocation of `print_n()` returns `None` to the 2nd call. The second call hits the end of the function and returns None to the first call. The first call to `print_n()` hits the end and returns None. So the result of that initial call to `print_n()` was `None`.

Now we're back at the beginning, essentially calling `do_n(None, 2)`

Since it's expecting its first argument to be callable (because on line 10, you try to call it), you get your `TypeError`.

Easiest thing to do is write a wrapper function that takes no arguments, since that's what `function()` expects: no arguments.

It might look like
``` python3
def wrapper():
	print_n('Hello', 2)
```

Then you just pass that wrapper to `do_n`:
`do_n(wrapper, 2)`

The real question here is, why are these functions recursive? The answer might be "because that's what the book wanted me to do," and if so, fine. If not... don't do that. A good old-fashioned for loop will get the job done just fine in this case, and is much easier to read and debug.

**Comment by rbanders** [comment]
wrapper function solves the problem.  The textbook is teaching about recursion and why sometimes it's good and mostly it's not, that's why these functions are recursive instead of for loops.  Thanks for the assistance!
